// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FM6IlmD1CMWBKLdg9Bq-raElK0MRkgo',
    appId: '1:966700247743:web:b71ce2b81ae61b1def740a',
    messagingSenderId: '966700247743',
    projectId: 'real-app-710f5',
    authDomain: 'real-app-710f5.firebaseapp.com',
    databaseURL:
        'https://real-app-710f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-app-710f5.appspot.com',
    measurementId: 'G-50WMCVXEEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIw--dBhP2I3kK5hzhKfI0NQSgwpynvkw',
    appId: '1:966700247743:android:0332da5f7471cecbef740a',
    messagingSenderId: '966700247743',
    projectId: 'real-app-710f5',
    databaseURL:
        'https://real-app-710f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-app-710f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArW99HoO6mj8CvdRPgUEJ6MaiBWpVl3VE',
    appId: '1:966700247743:ios:203e805a7600fa8aef740a',
    messagingSenderId: '966700247743',
    projectId: 'real-app-710f5',
    databaseURL:
        'https://real-app-710f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-app-710f5.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArW99HoO6mj8CvdRPgUEJ6MaiBWpVl3VE',
    appId: '1:966700247743:ios:203e805a7600fa8aef740a',
    messagingSenderId: '966700247743',
    projectId: 'real-app-710f5',
    databaseURL:
        'https://real-app-710f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-app-710f5.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9FM6IlmD1CMWBKLdg9Bq-raElK0MRkgo',
    appId: '1:966700247743:web:7b67770ff1ffba7eef740a',
    messagingSenderId: '966700247743',
    projectId: 'real-app-710f5',
    authDomain: 'real-app-710f5.firebaseapp.com',
    databaseURL:
        'https://real-app-710f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-app-710f5.appspot.com',
    measurementId: 'G-VLJ6JL0MPW',
  );
}
